version: '3.6'

services:
  Elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      #set memory usage
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk

  Logstash:
    image: logstash:7.17.9
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/:/logstash_dir
    #conf of logstash that needs to be done when logstash is starting
    #its about pipeline content
    command: logstash -f /logstash_dir/logstash.conf
    #some of the things in logstash.conf will be mapped to Elasticsearch container, so it can send data to Elasticsearch
    depends_on:
      - Elasticsearch
    ports:
      - '9600:9600'
    environment:
      #set memory usage
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  Kibana:
    image: kibana:7.17.9
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - Elasticsearch
    networks:
      - elk

  MinIO:
    image: minio/minio:RELEASE.2024-07-15T19-02-30Z
    container_name: minio
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    #every document stored in minIO will be stored here
    volumes:
      - ./minio_storage:/data
    command: server --console-address ":9001" /data
    env_file: .env
    networks:
      - elk

volumes:
  elastic_data: { }

networks:
  elk: